name: soma_facil
description: "Soma Fácil - Calculadora de Compras Inteligente"
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/web/
    - assets/web/assets/
